### PR TITLE
Added a new s3 bucket to hold server access logs

### PR DESCRIPTION
**Pull request by wanieldilson**
## What did I change

The penetration test required Server Access logging be enabled on the s3 bucket that holds Cloudtrail logs.  Amazon recommends a separate bucket is created for this purpose.  

The added code creates that bucket, assigns the log-delivery-write acl to it and blocks all public access as per the requirements from the pen test.  Finally, a "logging" block is added to the current s3 bucket with the newly created bucket as it's target.

### CODE REVIEW

**Comment by wanieldilson** [comment]
As this change is relating to the Cloudtrail log shipping, must the tfvar `enable_cloudtrail_log_shipping_to_cloudwatch` be manually set to `true` within parameter store for this to apply?

**Comment by neilkidd** [comment]
> As this change is relating to the Cloudtrail log shipping, must the tfvar `enable_cloudtrail_log_shipping_to_cloudwatch` be manually set to `true` within parameter store for this to apply?

The [buildspec.yml](https://github.com/ministryofjustice/staff-device-logging-infrastructure/blob/afa881f26615084669705838499dd0c04504d3f3/buildspec.yml#L9) explicity sets the value to true, in production like environments, and is only overridden "locally" in `tfvars.tf` - this is because there are cloudtrail limits that were being exceeded in the dev account.

**Review by neilkidd — APPROVED** [review]
👍

**Comment by wanieldilson** [comment]
> > As this change is relating to the Cloudtrail log shipping, must the tfvar `enable_cloudtrail_log_shipping_to_cloudwatch` be manually set to `true` within parameter store for this to apply?
> 
> The [buildspec.yml](https://github.com/ministryofjustice/staff-device-logging-infrastructure/blob/afa881f26615084669705838499dd0c04504d3f3/buildspec.yml#L9) explicity sets the value to true, in production like environments, and is only overridden "locally" in `tfvars.tf` - this is because there are cloudtrail limits that were being exceeded in the dev account.

Thanks @neilkidd, I see it now in the buildspec! Cleared that up.

**Pull request merged**
